
auto:merge:job:
  script:
    - |
      remove_branch=false
      if [[ "$MERGE_BRANCH_ACTION" == "delete" ]]; then
        remove_branch=true
      fi
    - 'opened_merge_requests=$(curl -k -H "Authorization: Bearer $PROJECT_TOKEN" $CI_API_V4_URL/projects/"$CI_PROJECT_ID"/merge_requests?state=opened)'
    - |
      for iid in $(echo "$opened_merge_requests" | jq '.[] | .iid'); do
        curl -k --fail -X PUT -H "Authorization: Bearer $PROJECT_TOKEN" \
          -d skip_ci=true \
          $CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$iid/rebase      
        curl -k -X POST -H "Authorization: Bearer $PROJECT_TOKEN" \
          $CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$iid/approve
        curl -k -X PUT -H "Authorization: Bearer $PROJECT_TOKEN" \
          -d merge_when_pipeline_succeeds=true \
          -d should_remove_source_branch=$remove_branch \
          -d squash_commit_message="$CI_COMMIT_MESSAGE" \
          -d squash=true \
          $CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$iid/merge 
      done
  rules:
    - when: always
