.template-variables: &template-variables
  variables:
    CHANNEL: release
    KUBE_CONTEXT: dev/kubernetes-agent-config:kubernetes-agent-prod

.template-rules: &template-rules
  if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_REF_PROTECTED == "true"
  <<: *template-variables

Build artifact:
  image:
    name: gradle
    entrypoint: [ "" ]
  cache:
    key: "$CI_PROJECT_ID"
    paths:
      - ./cache/
  script:
    - gradle buildPlugin -g ./cache/
  artifacts:
    paths:
      - "build/distributions/*.*"

#push artifact:
#  script:
#    - PLUGIN_VERSION=$(grep pluginVersion ./gradle.properties |  cut -d'=' -f2- | xargs)
#    - >
#      curl -v -k --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}"
#      --upload-file $(find ./build/distributions/ -type f -name '*.*')
#      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${PLUGIN_VERSION}/README.md"
#  needs:
#    - "Build artifact"

#push artifact:
#  script:
#    - PLUGIN_VERSION=$(grep pluginVersion ./gradle.properties |  cut -d'=' -f2- | xargs)
#    - >
#      curl -v -k --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}"
#      --upload-file ./README.md
#      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${PLUGIN_VERSION}/README.md"
#  needs:
#    - "Build artifact"

