
release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - PLUGIN_VERSION=$(grep pluginVersion ./gradle.properties |  cut -d'=' -f2- | xargs)
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '${RELEASE_VERSION}.$CI_PIPELINE_IID'
    description: '${RELEASE_VERSION}.$CI_PIPELINE_IID'
    assets:
      links:
        - name: '${CI_PROJECT_NAME}'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${RELEASE_VERSION}/README.md'